# Домашнее задание "Основные математические понятия".

## Уровень 0:


Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

[Игра в имитацию](https://www.kinopoisk.ru/film/635772/)

[Ярость](https://www.kinopoisk.ru/film/740644/)

[12 лет рабства](https://www.kinopoisk.ru/film/606646/)

[Однажды в Голливуде](https://www.kinopoisk.ru/film/1047883/)

```
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде
```



In [1]:
import numpy as np
film_1 = np.array([0,0,0,0,1,0])
film_2 = np.array([0,1,0,1,0,0])
film_3 = np.array([0,0,1,1,1,0])
film_4 = np.array([1,0,0,1,0,1])

### Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [2]:
cosine = film_2 @ film_3 / (np.linalg.norm(film_2) * np.linalg.norm(film_3))
angle = np.degrees(np.arccos(np.clip(cosine, -1, 1)))
assert np.isclose(cosine, 1 / np.sqrt(6))
print(f'Косинусная мера: {cosine:.6f}; угол: {angle:.6f}°')

Косинусная мера: 0.408248; угол: 65.905157°


## Уровень 1:

### Задание 2

Вычислить с помощью Python значение первой производной для функции $8x(x+3)^2$ в точке $x=1$


In [3]:
import sympy as sp
x = sp.symbols('x')
f = 8*x*(x+3)**2
derivative = sp.diff(f, x)
value = derivative.subs(x, 1)
assert value == 192
display(derivative, value)

8*x*(2*x + 6) + 8*(x + 3)**2

192

### Задание 3


Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [4]:
matrix = np.vstack([film_1, film_2, film_3, film_4])
result = np.array([1,2,3,4]) @ matrix
assert np.array_equal(result, [4,2,3,9,4,4])
print(matrix)
print(result)

[[0 0 0 0 1 0]
 [0 1 0 1 0 0]
 [0 0 1 1 1 0]
 [1 0 0 1 0 1]]
[4 2 3 9 4 4]


## Решение и проверка

Решение подготовлено AI по запросу владельца репозитория. Выполнение подтверждает работоспособность кода; самостоятельное владение материалом не оценивалось.

Скалярное произведение равно 1, нормы — √2 и √3. Производная: 24x² + 96x + 72; в точке 1 равна 192.