# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
import numpy as np
A = np.arange(1, 10).reshape(3,3)
B = A + np.eye(3)
product = B @ np.array([1,2,3])
transpose = B.T
inverse = np.linalg.inv(B)
assert np.allclose(B @ inverse, np.eye(3))
assert np.array_equal(product, [15,34,53])
for title, value in [('A',A), ('A + I',B), ('Произведение',product), ('Транспонирование',transpose), ('Обратная',inverse)]:
    print(title, '\n', value)

A 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A + I 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Произведение 
 [15. 34. 53.]
Транспонирование 
 [[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]
Обратная 
 [[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [2]:
m = np.array([[2,2],[1,3]])
values, vectors = np.linalg.eig(m)
assert np.allclose(m @ vectors, vectors @ np.diag(values))
assert np.allclose(np.sort(values), [1,4])
print('Собственные значения:', values)
print('Собственные векторы — столбцы:', vectors)

Собственные значения: [1.+0.j 4.+0.j]
Собственные векторы — столбцы: [[-0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j -0.70710678+0.j]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [3]:
C = np.array([[1,1],[1,2]])
assert np.all(C != 0) and np.isclose(np.linalg.det(C), 1)
print(C, 'det =', np.linalg.det(C))

[[1 1]
 [1 2]] det = 1.0


## Решение и проверка

Решение подготовлено AI по запросу владельца репозитория. Выполнение подтверждает работоспособность кода; самостоятельное владение материалом не оценивалось.

Собственные значения 1 и 4. Соответствующие направления векторов: (−2, 1) и (1, 1).